import { Request, Response } from 'express';
import { MomentaicWebhookService } from '../services/MomentaicWebhookService';

export const momentaicController = {
    // POST /api/v1/momentaic/characters/sync
    syncCharacter: async (req: Request, res: Response) => {
        try {
            const { character_id, name, dna } = req.body;

            if (!character_id || !name) {
                return res.status(400).json({ success: false, message: 'Missing character_id or name' });
            }

            // Inside Yokaizen, we would theoretically upsert this to a Characters table
            // For now, we simulate the sync
            console.log(`[Momentaic Bridge] Synced Character: ${name} (${character_id})`);
            console.log(`[Momentaic Bridge] DNA:`, dna);

            return res.status(200).json({
                success: true,
                message: 'Character synced successfully',
                data: { character_id, status: 'synced', timestamp: new Date().toISOString() }
            });
        } catch (error) {
            console.error('[Momentaic Bridge] Error syncing character:', error);
            return res.status(500).json({ success: false, message: 'Internal server error' });
        }
    },

    // POST /api/v1/momentaic/tasks/trigger
    triggerTask: async (req: Request, res: Response) => {
        try {
            const { character_id, agent_type, task_description, parameters } = req.body;

            if (!character_id || !agent_type) {
                return res.status(400).json({ success: false, message: 'Missing character_id or agent_type' });
            }

            const jobId = `job_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;

            console.log(`[Momentaic Bridge] Task Triggered: ${agent_type} for ${character_id}`);
            console.log(`[Momentaic Bridge] Description: ${task_description}`);

            // Simulate the AgentExecutor processing the task asynchronously
            // and the campaignWorker firing the task.completed webhook when finished.
            setTimeout(() => {
                const mockResult = {
                    video_url: `s3://bucket/${character_id}_tiktok_${jobId}.mp4`,
                    caption: "Generated by Yokaizen AgentExecutor! 🚀",
                    cost_usd: 0.45
                };
                MomentaicWebhookService.dispatchTaskCompleted(jobId, agent_type, mockResult);
            }, 5000); // Simulate 5 seconds of work

            return res.status(202).json({
                success: true,
                message: 'Task accepted for execution',
                data: { job_id: jobId, status: 'queued' }
            });
        } catch (error) {
            console.error('[Momentaic Bridge] Error triggering task:', error);
            return res.status(500).json({ success: false, message: 'Internal server error' });
        }
    },

    // GET /api/v1/momentaic/tasks/:job_id/status
    getTaskStatus: async (req: Request, res: Response) => {
        try {
            const { job_id } = req.params;

            return res.status(200).json({
                success: true,
                data: {
                    job_id,
                    status: 'processing', // Mock status
                    progress: 50
                }
            });
        } catch (error) {
            console.error('[Momentaic Bridge] Error getting task status:', error);
            return res.status(500).json({ success: false, message: 'Internal server error' });
        }
    }
};
